# Generated by Django 5.0.6 on 2024-05-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_user_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=100, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=100, max_length=250),
            preserve_default=False,
        ),
    ]
