# Generated by Django 5.0.6 on 2024-05-28 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_account_user_account_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.bank'),
            preserve_default=False,
        ),
    ]
