# Generated by Django 5.0.6 on 2024-05-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
